name: 邀请加入水系社区
description: 我很乐意加入水系社区并为社区做出贡献
title: "请邀请我成为水系历史骰主或加入社区并允许我为社区做出贡献"
labels: [invitation]
assignees: [HsiangNianian]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: 输入你的名字
    validations:
      required: true
  - type: input
    id: qq_id
    attributes:
      label: QQ ID (if applicable)
      placeholder: 输入你的QQ账号
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: 你想以怎样的身份进入水系社区？（默认：遗产骰主）
      options:
        - 遗产骰主
        - 贡献者
        - 核心成员（审核严格）
    validations:
      required: true
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: 你为什么想加入水系社区？
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        你也可以加入水系用户群(126211793)或者访问水系官网(<hydroroll.retrofor.space>)。
